/**
 * A way out of the exported history page.
 *
 * The page is generated by the agent package and has no control that leaves
 * it. In a browser that costs nothing -- the tab bar is right there -- but an
 * installed application has no tab bar, no address bar and no back button, so
 * opening it was a one-way door: the only exit was force-quitting the app.
 *
 * Injected as a string for the same reason the recursion fix above is: the
 * template lives in node_modules and would be overwritten on install.
 *
 * The handler tries the three ways back in order of what actually works.
 * `history.back()` is the one that applies when the page replaced the app in
 * the same window, which is what an installed application now does.
 */
const CLOSE_CONTROL = `
<style>
#pai-export-close {
  position: fixed;
  top: calc(12px + env(safe-area-inset-top));
  right: 12px;
  z-index: 2147483647;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 30px;
  height: 30px;
  padding: 0;
  border: none;
  border-radius: 50%;
  /* Enough of a disc to read as a button, not enough to look like it belongs
     to an application that is no longer around this page. */
  background: color-mix(in srgb, currentColor 12%, transparent);
  box-shadow: inset 0 0 0 1px color-mix(in srgb, currentColor 22%, transparent);
  -webkit-backdrop-filter: blur(6px);
  backdrop-filter: blur(6px);
  color: currentColor;
  opacity: 0.7;
  font: 400 22px/1 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  cursor: pointer;
}

#pai-export-close:hover,
#pai-export-close:active {
  opacity: 1;
}
</style>
<button id="pai-export-close" type="button" aria-label="Close" title="Close">&times;</button>
<script>
document.getElementById("pai-export-close").addEventListener("click", function () {
  if (history.length > 1) { history.back(); return; }
  window.close();
  setTimeout(function () { location.href = "/"; }, 150);
});
</script>
`;

export function paiAddExportCloseControl(html: string): string {
  const end = html.lastIndexOf("</body>");
  if (end === -1) return html + CLOSE_CONTROL;
  return html.slice(0, end) + CLOSE_CONTROL + html.slice(end);
}
